---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-example-config
data:
  nginx.conf: |
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        server {
            listen       8888 default_server;
            listen       [::]:8888 default_server;
            server_name  _;
            root   html;
            index  index.html index.htm;

            location / {
            }

            error_page 404 /404.html;
                location = /40x.html {
            }

            error_page 500 502 503 504 /50x.html;
                location = /50x.html {
            }
        }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-nginx
spec:
  containers:
  - name: test-container-nginx
    image: registry.access.redhat.com/ubi8/nginx-120
    command: ["nginx"]
    args: ["-g", "daemon off;"]
    ports:
    - containerPort: 8888
    volumeMounts:
    - name: nginx-example-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-example-config
    configMap:
      name: nginx-example-config
  imagePullPolicy: Always
  nodeName: <NODE_SERVER>
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-client
spec:
  containers:
  - name: test-container-client
    image: registry.access.redhat.com/ubi8
    command: ["sleep"]
    args: ["3600"]
  imagePullPolicy: Always
  nodeName: <NODE_CLIENT>

